#pragma config(StandardModel, "Clawbot IQ")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float encodedMotor; // variable to hold the `getMotorEncoder` value
float rotationUnit; // variable to hold the data to be displayed

// this function will return float value
float getMotorEncoderThenReturn()
{
	setMultipleMotors(50, leftMotor, rightMotor, noMotor, noMotor);
	waitUntil (getMotorEncoder(leftMotor) >= 360);
	stopAllMotors();
	encodedMotor = getMotorEncoder(leftMotor);
	
	return encodedMotor;
	
}

// this function will not return anything
// rather will just execute the commands here
void calculateDistanceThenDisplay()
{
	rotationUnit = getMotorEncoderThenDisplay()/360;
	displayVariableValues(line1, rotationUnit);
	wait(5, seconds);	
}

task main()
{
getMotorEncoderThenReturn();
calculateDistanceThenDisplay();
}
