#pragma config(StandardModel, "Clawbot IQ")
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

void displayDataWhileMoving() {
	resetMotorEncoder(leftMotor);
	float encodedMotor;
	while (getMotorEncoder(leftMotor) <= 360) {
		setMultipleMotors(20, leftMotor, rightMotor, noMotor, noMotor);
		encodedMotor = getMotorEncoder(leftMotor);
		displayVariableValues(line1, encodedMotor);
	}
}

task main()
{
	displayDataWhileMoving();
	resetMotorEncoder(leftMotor);
	stopAllMotors();

	wait(5, seconds);

}
