#pragma config(StandardModel, "Clawbot IQ")
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

void displayDataWhileMoving() {
	resetMotorEncoder(leftMotor);
	float encodedMotor;
	while ( getBumperValue(bumpSwitch) == 0 ) {
		setMultipleMotors(20, leftMotor, rightMotor, noMotor, noMotor);
		encodedMotor = getMotorEncoder(leftMotor);
		displayVariableValues(line1, encodedMotor);
	}
}

task main()
{
	displayDataWhileMoving();
	
	//hang the program a little bit
	//for data display
	displayVariableValues(line1, encodedMotor);
	wait(5, seconds);

}
