#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void lightLEDGreen() {
	waitUntil(getTouchLEDValue(touchLED) == 1 );

	setTouchLEDColor(touchLED, colorGreen);
	wait(5, seconds);
	setTouchLEDColor(touchLED, colorNone);
}

void lightLEDRedIF() {
	wait(5, seconds);
	if (getTouchLEDValue(touchLED) == 1) {

		setTouchLEDColor(touchLED, colorRed);
		wait(5, seconds);
		setTouchLEDColor(touchLED, colorNone);
	}

}

void waitUntilBumper() {
	moveMotor(armMotor, 400, degrees, 50);

	setMultipleMotors(50, rightMotor, leftMotor, noMotor, noMotor);
	waitUntil( getBumperValue(bumpSwitch) == 1 );
	stopAllMotors();
}

task main()
{
	lightLEDGreen();
	lightLEDRedIF();
	waitUntilBumper();
}
