#pragma config(StandardModel, "Clawbot IQ With Sensors")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void displayDataWhileMoving() {
	//since it will turn left,
	//we use the right motor
	//for the motor encoder
	resetMotorEncoder(rightMotor);
	float encodedMotor;

	//raise the arm for the bumper switch
	moveMotor(armMotor, 400, degrees, 50);

	//while the bumper switch is not
	//yet pressed, the robot will move
	//forward and display green on the
	//touchLED
	while ( getBumperValue(bumpSwitch) == 0 ) {

		//the if statement can be skipped when
		//there is no touch input, hence it will
		//continue moving forward
		//but if there is the touch input,
		//will turn left
		if (getTouchLEDValue(touchLED) == 1) {
			//just a demonstration that
			//we can put several if statements			
			//inside this while loop,
			//in this case just turning left			

			//basic turning will depend more
			//on the power level, battery and
			//friction,
			//but the ideal in the virtual world
			//is 250 degrees,
			turnLeft(260, degrees, 100);
		}

		setMultipleMotors(20, leftMotor, rightMotor, noMotor, noMotor);

		//display motor encoder value while
		//the robot is moving forward
		encodedMotor = getMotorEncoder(rightMotor);
		displayVariableValues(line1, encodedMotor);
		setTouchLEDColor(touchLED, colorGreen);
	}

	//this point will be reached if this function goes out of the
	//while loop
	setMultipleMotors(0, leftMotor, rightMotor, noMotor, noMotor);
	setTouchLEDColor(touchLED, colorRed);
	wait(5, seconds);
	setTouchLEDColor(touchLED, colorNone);
}

task main()
{
	displayDataWhileMoving();
}
